# Generated by Django 3.1.2 on 2020-10-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bunny_toys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunny_Breeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
    ]
