# Generated by Django 3.1.2 on 2020-10-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_bunny_breeds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bunny_Breeds',
            new_name='Bunny_Breed',
        ),
    ]
