# Generated by Django 3.1.2 on 2020-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201008_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunny_breed',
            name='color',
            field=models.CharField(max_length=250),
        ),
    ]
